services:
  agentic-society-web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    volumes:
      # 挂载数据目录，确保数据持久化
      - ./data:/app/data
    restart: unless-stopped

  # 可选：如果需要数据库，可以添加PostgreSQL服务
  # postgres:
  #   image: postgres:13
  #   environment:
  #     POSTGRES_DB: agentic_society
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: