LANGUAGES = {
    'zh': {
        'file': '文件',
        'sampling': '抽样',
        'close': '关闭',
        'exit': '退出',
        'analysis': '分析',
        'analysis_exp': '实验分析',
        'personality': '测试结果浏览',
        'personality_analysis': '性格分析',
        'personality_stats': '性格统计',
        'evaluation': '评估',
        'base': '基础',
        'persona': '角色',
        'question': '问题',
        'question_group': '问题组',
        'persona_group': '角色组',
        'experimentlist': '实验列表',
        'experiment': '实验',
        'tree_root': 'Agentic Society',
        'language': '语言',
        'menu_language': '语言/Language',
        'create': '生成',
        'refresh': '刷新',
        'summary': '统计摘要',
        'trait_names': ['神经质', '外向性', '开放性', '宜人性', '尽责性'],
        'columns': ('性格维度', '均值', '方差', '标准差', '样本数'),
        'summary_head': '性格维度统计摘要：',
        'insight': '统计洞察：',
        'max_mean': '• 平均分最高的维度',
        'min_mean': '• 平均分最低的维度',
        'error': '获取统计数据时出错：',
        'plot_title': '性格维度随年龄变化',
        'age': '年龄',
        'score': '得分',
        'distance_table_title': 'Average Distance from Human Curve (at ages 20-70)',
    },
    'en': {
        'file': 'File',
        'sampling': 'Sampling',
        'close': 'Close',
        'exit': 'Exit',
        'analysis': 'Analysis',
        'analysis_exp': 'Experiment Analysis',
        'personality': 'Test Result Browser',
        'personality_analysis': 'Personality Analysis',
        'personality_stats': 'Personality Statistics',
        'evaluation': 'Evaluation',
        'base': 'Base',
        'persona': 'Persona',
        'question': 'Question',
        'question_group': 'Question Group',
        'persona_group': 'Persona Group',
        'experimentlist': 'Experiment List',
        'experiment': 'Experiment',
        'tree_root': 'Agentic Society',
        'language': 'Language',
        'menu_language': '语言/Language',
        'create': 'Create',
        'refresh': 'Refresh',
        'summary': 'Summary',
        'trait_names': ['Neuroticism', 'Extraversion', 'Openness', 'Agreeableness', 'Conscientiousness'],
        'columns': ('Trait', 'Mean', 'Variance', 'Std', 'N'),
        'summary_head': 'Personality Dimension Summary:',
        'insight': 'Insights:',
        'max_mean': '• Highest mean',
        'min_mean': '• Lowest mean',
        'error': 'Error fetching statistics:',
        'plot_title': 'Personality vs Age',
        'age': 'Age',
        'score': 'Score',
        'distance_table_title': 'Average Distance from Human Curve (at ages 20-70)',
    }
} 